# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EnergyDataModel',
                'doc_host': 'https://sebaheg.github.io',
                'git_url': 'https://github.com/sebaheg/EnergyDataModel',
                'lib_path': 'EnergyDataModel'},
  'syms': {'EnergyDataModel.core': {'EnergyDataModel.core.foo': ('core.html#foo', 'EnergyDataModel/core.py')}}}
